---
- name: Check if ansible version is equal or greater than 2.11
  when: ansible_version.full is ansible.builtin.version('2.11','<')
  tags: pgbackup,pgbckp_ch_sw_vers
  ansible.builtin.fail:
    msg: "Ansible core should be equal or greater than 2.11"

- name: Check if python is equal or greater than 3
  when: ansible_python.version.major is ansible.builtin.version('3','<')
  tags: pgbackup,pgbckp_ch_sw_vers
  ansible.builtin.fail:
    msg: "Python should be equal or greater than 3"

# tasks file for pgbackup
- name: Install backup tool
  tags: pgbackup,pgbckp_install
  ansible.builtin.package:
    name: "{{ pgbackup_packages }}"
    state: present

- name: Configure backup tool (pgbackrest and main config of barman)
  when: pgbackup_tool != "pg_probackup"
  tags: pgbackup,pgbckp_config
  ansible.builtin.template:
    src: "{{ pgbackup_templates_dir }}/{{ pgbackup_tool }}.cfg.j2"
    dest: "{{ pgbackup_config_dir }}/{{ pgbackup_config_file }}"
    mode: "{{ pgbackup_config_file_mode }}"
    owner: "{{ pgbackup_config_file_owner }}"
    group: "{{ pgbackup_config_file_group }}"
    validate: "{{ pgbackup_config_validate_command }}"

- name: Configure custom instances if defined
  when: pgbackup_instances.mode == "separate"
  tags: pgbackup,pgbckp_config
  ansible.builtin.template:
    src: "{{ pgbackup_templates_dir }}/{{ pgbackup_tool }}-instance.cfg.j2"
    dest: "{{ pgbackup_custom_config_dir }}/{{ item.name }}.conf"
    mode: "{{ pgbackup_config_file_mode }}"
    owner: "{{ pgbackup_config_file_owner }}"
    group: "{{ pgbackup_config_file_group }}"
    validate: "{{ pgbackup_config_validate_command }}"
  loop: "{{ pgbackup_instances }}"

- name: Check if base directories exist
  when: item.type == "dir" or item.type == "directory"
  tags: pgbackup,pgbckp_data_dirs
  ansible.builtin.file:
    path: "{{ item.point }}"
    state: directory
    mode: "{{ pgbackup_config_file_mode }}"
    owner: "{{ pgbackup_config_file_owner }}"
    group: "{{ pgbackup_config_file_group }}"
  loop: "{{ pgbackup_base_dest }}"

- name: Init tool
  tags: pgbackup,pgbckp_init
  ansible.builtin.command: "{{ pgbackup_init_command }} {{ item.name }}"
  changed_when: true
  loop: "{{ pgbackup_instances }}"
  when: pgbackup_init_command is defined and pgbackup_init_command | length > 0

- name: Create backup instances
  tags: pgbackup,pgbckp_create
  ansible.builtin.command: "{{ pgbackup_create_command }} {{ item.name }}"
  changed_when: true
  loop: "{{ pgbackup_instances }}"
  when: pgbackup_create_command is defined and pgbackup_create_command | length > 0

- name: Create schedule for full backups
  tags: pgbackup,pgbckp_full_schedule
  ansible.builtin.cron:
    name: "Full backup of {{ item.name }}"
    cron_file: "{{ pgbackup_config_file_owner }}"
    user: "{{ pgbackup_config_file_owner }}"
    job: "{{ item.full.backup_command }}"
    minute: "{{ item.full.minute | default(omit) }}"
    hour: "{{ item.full.hour | default(omit) }}"
    day: "{{ item.full.day | default(omit) }}"
    weekday: "{{ item.full.weekday | default(omit) }}"
    month: "{{ item.full.month | default(omit) }}"
    special_time: "{{ item.full.special_time | default(omit) }}"
  loop: "{{ pgbackup_instances }}"

- name: Create schedule for incremental backups
  tags: pgbackup,pgbckp_incr_schedule
  ansible.builtin.cron:
    name: "Incremental backup of {{ item.name }}"
    cron_file: "{{ pgbackup_config_file_owner }}"
    user: "{{ pgbackup_config_file_owner }}"
    job: "{{ item.incr.backup_command }}"
    minute: "{{ item.incr.minute | default(omit) }}"
    hour: "{{ item.incr.hour | default(omit) }}"
    day: "{{ item.incr.day | default(omit) }}"
    weekday: "{{ item.incr.weekday | default(omit) }}"
    month: "{{ item.incr.month | default(omit) }}"
    special_time: "{{ item.incr.special_time | default(omit) }}"
  when: item.incr is defined
  loop: "{{ pgbackup_instances }}"
